image: docker:latest

services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PWD

build:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
    - docker tag "$CI_REGISTRY_IMAGE" "$DOCKER_HUB_USER/mirror-docker-image"
    - docker push "$DOCKER_HUB_USER/mirror-docker-image"