batch:
  maxConcurrentDownloads: 5
  targetRegistry: registry.saas.hand-china.com/tools
  images:
    - "redis:5.0.3"
    - "mysql:5.7.24"
    - "nginx:1.15.7"
single:
  - image: "tomcat:7.0.92-jre8"
    targetRegistry: registry.saas.hand-china.com/tools